---

name: Packer GitHub Actions
#uses: hashicorp/packer-github-actions@v0.2.0

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
      - packer/alluvium-base.pkr.hcl

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      # DISABLE - Only Works With JSON
      # - name: Fix Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: fix

      # init
      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          arguments: -upgrade
          target: packer/alluvium-base.pkr.hcl


      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/alluvium-base.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: alluvium-base.pkr.hcl
          working_directory: packer
        env:
          PACKER_LOG: 1
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # additional steps to process artifacts

