name: "Terraform Apply"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}

jobs:
  fix_formatting:
    runs-on: ubuntu-latest
    name: Fix terraform formatting in example terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          workspace: alluvium-infrastructure
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          label: production
          workspace: alluvium-infrastructure
          auto_approve: true